The drama started Tuesday after Portuguese authorities would n't let Bolivian President Evo Morales ' plane land in Lisbon for refueling while on his way back from a conference in Russia , Bolivian Defense Minister Ruben Saavedra told CNN en Español .

With no clear path home available , the flight 's crew made an emergency landing in Austria .

`` We do not know who has invented this lie . Someone who wants to harm our country . This information that has been circulated is malicious information to harm this country . ''

Late Wednesday morning , Spain agreed to let Morales ' plane stop in the Canary Islands on its way home , the Spanish Foreign Ministry said . The plane landed there as planned Wednesday , and subsequently took off for Fortaleza , Brazil , where it landed and refueled again Wednesday evening , Bolivia TV reported .

The presidential plane was scheduled to return to Bolivia on Wednesday night . The state broadcaster showed crowds of supporters brandishing Bolivian flags and awaiting Morales ' return .

At the El Alto International Airport outside La Paz , the state broadcaster showed crowds waved signs saying , `` Sovereign Bolivia , colony no more '' and , `` You are not alone . The people of the world are with you . ''

Opinion : Snowden and a muzzle free press

The plane spent more than 10 hours in Vienna , where Austrian officials confirmed that Snowden was not aboard after Morales allowed an Austrian airport police officer onto his plane for a `` voluntary check , '' Interior Ministry spokesman Karl-Heinz Grundboeck said .

As Morales resumed his journey , differing accounts emerged of what happened .

The authorization was granted as soon as French authorities were informed that the plane was the Bolivian president 's aircraft , the ministry said .

France `` never intended to deny president Morales 's plane access to -LRB- its -RRB- airspace , '' and the Bolivian leader is welcome in France , Fabius said .

Bolivian minister : U.S. behind Snowden rumor

Bolivian authorities are investigating the source of the rumors about Snowden . Saavedra , the Bolivian defense minister , told CNN en Español that he believed the U.S. was behind them .

`` This is a lie , a falsehood , '' he said . `` It was generated by the U.S. government . ''

It is n't the first time Bolivian authorities have accused U.S. officials of trying to meddle with their presidential plane .

Outrage in Latin America

`` The president has been kidnapped by imperialism , and he is being held in Europe , '' he said in a televised address late Tuesday night . The vice president called for workers worldwide to protest `` this act of imperial arrogance . ''

He said Bolivia would complain about the incident to the United Nations .

The situation drew a stern rebuke from Brazilian President Dilma Rousseff , who said the incident was `` life-threatening '' for the Bolivian leader .

`` The Brazilian government expresses its outrage and condemnation of the embarrassment imposed on President Evo Morales by some European countries , '' she said in a statement Wednesday . `` The pretext that led to this unacceptable behavior -- the supposed presence of Edward Snowden in the plane of the president -- was fictional and a serious disrespect to the law and to international practices and standards of civilized coexistence among nations . ''

The Union of South American Nations released a statement Wednesday saying the body `` rejects categorically the dangerous act '' of denying Morales ' plane access . The leaders of the UNASUR countries are scheduled to meet on Thursday meeting in Cochabamba , Bolivia , to discuss the matter .

By Wednesday evening , the presidents of Argentina , Venezuela , Peru , Suriname , Ecuador and Bolivia had confirmed their plans to attend , said Ecuadorian Foreign Minister Ricardo Patino , who called the situation `` very serious . ''

`` This constitutes an unacceptable , unfounded and arbitrary act which offends all of Latin America and the Caribbean , '' the ministry said in a statement .

So where is Snowden ?

` Unbowed ' Snowden seeks new havens

Morales , a left-leaning president who has long criticized the United States , had been attending a conference of gas-exporting countries in Russia , where he told the Russia Today news network that he would be willing to consider asylum for Snowden .

But Bolivian officials stressed that accusations that an official aircraft would harbor Snowden were baseless .

His comments came in a piece co-written with the secretary general of Reporters without Borders , Christophe Deloire , for French newspaper Le Monde .

European Union states should accord Snowden their warmest welcome , their article said . If he is abandoned in the international zone of Moscow 's Sheremetyevo International Airport , it will mean European countries are `` abandoning their principles and part of the reason for the EU , '' it said .

In recent days , a number of European nations have voiced concern about reports -- based on documents apparently provided by Snowden -- that the United States has been conducting surveillance on its European allies .

She was echoing remarks made by President Francois Hollande this week after the claims first appeared in German and British media .

Germany 's Economy Minister Philipp Roesler has said the reports of spying do influence the planned talks , said his spokesman , Adrian Toschev .

But the spokesman declined to back the French call for a delay to the talks , which are scheduled to begin Monday .

@highlight

NEW : Crowds of supporters await Morales ' return to Bolivia

@highlight

Brazil 's president says she is outraged , European countries ' behavior `` unacceptable ''

@highlight

The plane leaves Austria after officials check it and say Edward Snowden is n't on board

@highlight

Bolivia says France denied the plane entry into its airspace , but France says it did not

