-LRB- CNN -RRB- Imagine putting wings on the White House and getting it to fly around the world .

Now the Pentagon has announced the next generation of this world-class icon will be a military version of the 747-8 . For nearly 30 years , the current jumbo jet Air Force One has been a customized version of the 747-200B . The newer 747-8 is longer and more efficient than its older brother .

Let 's remind ourselves why the world is so fascinated with this flying technological marvel .

For more than half a century , passengers aboard the U.S. presidential aircraft have been witness to American history .

Consider the fact that all these things happened on an Air Force One :

-- Lyndon Johnson was sworn in as president .

-- LBJ let a reporter interview him in the plane 's stateroom , while dressed only in a towel .

-- President Richard Nixon became the first American president to visit China , where he historically opened the door to U.S.-Chinese relations .

-- Air Force One served as President George W. Bush 's command center during the first hours following the 9/11 attacks .

The 747-8 is made in the U.S. , which the Air Forced hinted was a plus .

When will the President get a new jumbo jet ? Hard to say . If everything goes smoothly , Boeing likely will work with the Air Force on hammering out a timeframe and production schedule .

Members of Congress , celebrities and advocates clamor for seats on it , to get rare access to the President -- arguably the most powerful person on the planet .

Officially , the aircraft is only called Air Force One while a sitting president is aboard . The presidential fleet includes several aircraft , other than the two 747s , that from time to time carry the `` Air Force One '' call sign .

For example , the technological wizardry onboard the present 747s got wide play in the 1997 Harrison Ford action movie `` Air Force One , '' in which the President 's jet is hijacked by Russian nationalists .

However , many of the more outlandish gizmos featured in the film owed more to , shall we say , artistic license than to airborne fact .

The plane for example has no escape pod . Nor is it equipped with parachutes -- the massive slipstream created by an aircraft the size of a 747 means they ca n't be used .

Designed to operate as independently as possible from ground services , the aircraft can fly halfway around the world without refueling .

They carry their own automated baggage loaders as well as built-in front and aft stairs enabling them to operate self-sufficiently at airports and airfields around the world , minimizing security risks .

Capable of in-flight refueling from airborne tankers , manufacturers say the aircraft has `` virtually unlimited range '' -- its passengers sustained by galleys capable of storing up to 2,000 meals at a time .

The entire aircraft is shielded against the effects of electromagnetic pulse -- a wave of energy generated by the detonation of a nuclear device that can disable unprotected electronics .

Also on board is a stateroom and conference rooms that can , should it ever be necessary , be converted into a fully functional airborne medical center .

CNN 's Joe Havely contributed to this report .

@highlight

Pentagon approves bigger version of the Boeing 747 as the new Air Force One

@highlight

Air Force One may be the most famous plane in the world

@highlight

Basically a White House with wings , it has been witness to American history

