-LRB- CNN -RRB- -- As a concept , recycling has lived and died many times throughout its 4,000-year old history . But it always re-emerges as an idea when humans need it most , such as during the Great Depression , and later during World War II , when American companies recycled or reused around 25 percent of the waste stream .

A sign in Cheshire , England signalling a recycling drop-off area .

What 's not to like about recycling ?

Not surprisingly , recycling also impacts pollution levels . BIR says producing paper from recycled paper as opposed to wood can slash air pollution by as much as 74 percent and water pollution by 35 percent ; while manufacturing recycled steel results in 86 percent less air pollution .

There are different types of pollution savings to be made , reducing the pollution generated by manufacturing the stuff in the first place . And then there is the pollution that results in dumping the waste in landfills , instead of recycling it . A recent report from the European Environment Agency -LRB- EEA -RRB- , for example , has predicted that greenhouse gas emissions from household waste will drop by more than 80 percent by 2020 -- largely because of increases in recycling levels which are diverting waste away from landfills .

And the carbon savings can be huge , even when a relatively small amount of effort has been made . The UK has one of Europe 's lowest recycling rates when it comes to municipal waste -- 27 percent . Yet , the impact on its carbon emissions has already become worthwhile , according to Waste & Resources Action Programme , or WRAP . WRAP says that these relatively minor efforts already mean a 10 million - to 15 million-ton reduction in carbon dioxide -LRB- CO2 -RRB- emissions a year -- the equivalent of taking 3.5 million cars off the road .

What about the costs ? One of the main objections to the recycling movement has been the cost factor . Throwing something away is obviously going to be a lot cheaper than going through the hassle of recycling it . And certain materials are going to be a lot tougher to recycle than others , driving up costs and energy spent . But , as a 2004 study by research group GPI Atlantic found out , there are many different ways to measure cost .

GPI concluded that Nova Scotia was in fact saving up to $ 125 million simply because it had embraced recycling .

The developing world 's gain ?

`` There is a lot to be learned from the developing world , '' the Observer quoted Friends of the Earth 's Claire Wilton as saying . `` Where a scavenger mentality , grassroots recycling and sheer necessity can lead to imaginative leaps in redeploying waste . ''

That being said , the economic impact may be welcomed by those in poorer countries sifting through everyone 's trash -- but the health impact still leaves a lot to be desired .

Around 70 percent of the world 's electronic waste ends up in southern China . A recent study by Hong Kong 's Baptist University found that the basic methods employed to recycle these items was having an unsettling effect on people living nearby , specifically women . Women in their mid-20s in one recycling site in Zheijiang Province were found to be carrying the highest levels of cancer-causing toxic chemicals like dioxins and furans than they had seen anywhere else in the world .

-LRB- Source : The Observer ; Friends of the Earth ; The Independent ; California Environmental Protection Agency ; National Recycling Coalition ; New Scientist ; BIR ; The Economist ; Bureau of International Recycling ; UNEP ; Wired -RRB-

@highlight

Recycling as a movement 4,000 years old

@highlight

More than 500 million tons of material recycled every year

@highlight

Recycling a boom industry in developing world

@highlight

Health risks arising from poor recycling operations in China

