Washington (CNN) -- President Obama announced $8.3 billion in loan guarantees Tuesday for two nuclear reactors to be built in Burke County, Georgia.

The loan guarantees will help create 3,500 on-site construction jobs and 850 permanent operations jobs, administration officials claimed. The reactors will help provide power to over 550,000 homes and 1.4 million people, it said.

The president acknowledged that construction of new nuclear facilities will meet with some political resistance. Nuclear development has traditionally been opposed by more progressive elements of the Democratic Party. But nuclear power, he said, remains the country's largest source of fuel that produces no carbon emissions.

"To meet our growing energy needs and prevent the worst consequences of climate change, we'll need to increase our supply of nuclear power. It's that simple," he said.

At the same time, the president argued, traditional Republican proponents of nuclear power should acknowledge that comprehensive energy legislation is needed to help provide incentives to make clean energy more profitable.

Any new nuclear facilities, he promised, will "be held to the highest and strictest safety standards."

Leading congressional Republicans -- including both Georgia senators -- were quick to praise Obama's decision.

"This announcement represents a step in the right direction," said Sen. Saxby Chambliss, R-Georgia. "The power generated by [the Burke County facility] is safe, reliable, emissions-free and environmentally responsible."

"The last thing Americans want is another government bailout for a failing industry, but that's exactly what they're getting from the Obama administration," energy analyst Ben Schreiber said in a press release issued this past weekend.

"The Department of Energy is putting taxpayers on the hook for bailing out costly and dangerous nuclear reactor projects when the loans used to finance those projects default. This is great news for Wall Street but a bad deal for Main Street."

The risk of default is high, Schreiber argued, while nuclear power "remains unsafe and dirty."

We are working "as hard and as fast as we can" to "recapture the lead in nuclear technology," Chu said. America has been "sitting on the sidelines... for far too long."

CNN's Suzanne Malveaux, Evan Glass, Deirdre Walsh and Alan Silverleib contributed to this report.

@highlight

NEW: Modern reactors far safer than pre-Three Mile Island reactors, energy secretary says

@highlight

NEW: Loan applications for more nuclear facilities being considered, Steven Chu says

@highlight

NEW: GOP senator from Georgia praises Obama's decision as "a step in the right direction"

@highlight

3,500 on-site construction jobs and 850 permanent operations jobs projected, officials say

