An ocean wave knocked three people into the Atlantic off Maine's Acadia National Park on Sunday.

Coast Guard rescuers plucked the three from the ocean after a wave swept them from a rocky ledge at the park, according to Sheridan Steele, the park's superintendent.

The conditions of the two survivors -- a 12-year-old girl and a man -- were not immediately available. No names were released.

Ocean waves also injured a few other people at the park, knocking them to the ground or into rocks and crevices, Steele said. Some were taken to a hospital with broken bones or other injuries, Steele said.

The victims were among several thousand people who were at the park late Sunday morning to watch the high waves that Hurricane Bill -- a Category 1 storm -- was producing offshore.

"Even though we try to warn people and try to get people to watch from a safe distance, we weren't able to contact everybody in time," Steele said Sunday evening.

The storm had maximum sustained winds near 75 mph, and was moving to the east-northeast near 40 mph the center reported. Bill would become a tropical storm if its winds fall below 74 mph.

"Weakening is forecast during the next 24 hours and Bill is expected to become extratropical on Monday," the center's 11 p.m. advisory said. "Large and dangerous swells generated by Hurricane Bill will continue to impact the Atlantic Maritimes of Canada overnight."

A tropical storm warning means tropical storm conditions are expected somewhere within the warning area within 24 hours.

"Large and dangerous swells generated by Hurricane Bill" were possible along those provinces Sunday night, and 2 to 6 inches of rain were possible in Newfoundland, the advisory said.

Earlier, the weather service warned that dangerous surf and "life-threatening rip currents" remained concerns along the U.S. East Coast. Rip currents are strong seaward flows of water that occur where there's a break in the shoreline. They are difficult to detect.  Watch a primer on rip currents »

The water is unsafe even for "strong swimmers," Massachusetts Gov. Deval Patrick warned Saturday.

Rain was scant in Chatham on Sunday morning as residents went about their normal business.

Doug Ricciardi, a cook at the Chatham Pier Fish Market, was making 5-gallon buckets of chowder, as he does every morning. He said he was expecting a typically busy day at the restaurant.  Watch how surf warnings persist in North Carolina »

Patrick O'Connell of Chatham said he has a house on nearby North Beach Island, and neither his nor his neighbor's house suffered any damage.

Smith said the beaches should reopen Monday at 2 p.m. after the heavy surf and rip currents pass.

The Coast Guard reported swells reached 18 feet about 15 miles off the Massachusetts coast early Sunday. The swells began diminishing around 3 a.m., and swells off the coast of Chatham on Sunday morning were 11 feet.  Watch the waves crash on Massachusetts beach »

The weather service reported that swells from Bill continued to affect Bermuda early Sunday, but should gradually diminish over the course of the day.

@highlight

NEW: One of three people in Maine swept into Atlantic Ocean by wave dies

@highlight

Victims were among people at state park to watch high waves from Hurricane Bill

@highlight

Storm skirts East Coast; Massachusetts residents carry on with daily lives

@highlight

Chatham, Massachusetts, harbormaster: "I think we really dodged a bullet"

